### ISSUE TITLE
Not Able to run tests

### ISSUE THREAD

**Issue by manojjenago** [rahulrathore44/SeleniumCucumber#4]
Hi ,
First of all thanks for providing a beautiful framework. However when I clone and want to tun the tests using `mvn clean generate-sources test`  I am getting the below error. I have added javax.xml.bind as dependencies but still fails. I have Jdk 11 installed. Please suggest. Also I did not see the report as shown . Please suggest 

`There was an error in the forked process
java.lang.NoClassDefFoundError: **javax/xml/bind/ValidationEventLocator`**

`There was an error in the forked process
java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventLocator
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at ru.yandex.qatools.allure.testng.AllureTestListener.onStart(AllureTestListener.java:66)
	at org.testng.TestRunner.fireEvent(TestRunner.java:959)
	at org.testng.TestRunner.beforeRun(TestRunner.java:629)
	at org.testng.TestRunner.run(TestRunner.java:595)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventLocator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)`

**Comment by rahulrathore44** [comment]
@manojjenago 

I fixed the dependency problem as well as the class loader problem. Can you give it one more try from your side?
**Note** - I am using the following version of JDK

`
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.15+10-adhoc..jdk11u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.15+10-adhoc..jdk11u, mixed mode)
`

Depending upon the class loader. The following line of code needs fine-tuning.

[ResourceHelper.java](https://github.com/rahulrathore44/SeleniumCucumber/blob/master/src/main/java/com/cucumber/framework/utility/ResourceHelper.java#L26)
